--- 
abstract: A perl interface to kotonoha.cc
author: Yasuhiro Matsumoto <mattn.jp@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Kotonoha
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Selector::XPath: 0.02
  HTML::TreeBuilder::XPath: 0.08
  WWW::Mechanize: 1.22
  perl: 5.8.1
  utf8: 1.04
version: 0.01a
